### ISSUE TITLE
os

### ISSUE THREAD

**Issue by yuliuyu** [GatoY/YOLOv3-pytorch-deepsort-iOS-Django#1]
Do I have to use a mac computer  to run your code? If I didn't have a mac computer, I can only use a sandbox environment for the demo and I can't relase the app to  ios,  right?

**Comment by GatoY** [comment]
Hi, u can run the algorithm only (Instruction is in readme.md already). I will upload my iOS application part and using instruction tomorrow. For OS, I don't know how to run iOS simulator on Windows.

**Comment by GatoY** [comment]
Application Part uploaded. Feel free to contact if there's any issue. Cheers! ;)
