### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by yuliuyu** [GatoY/YOLOv3-pytorch-deepsort-iOS-Django#2]
hi，I find your IOS file is empty, I can't  find project-tracking under Application/iOS/, Please upload files under IOS file,Thanks

**Comment by yuliuyu** [comment]
hi，I find your IOS file is empty, I can't find project-tracking under Application/iOS/, Please upload files under IOS file,Thanks

**Comment by GatoY** [comment]
Hi, the iOS part is no longer maintained. So I suggest focussing on the algorithm part.

**Comment by yuliuyu** [comment]
> Hi, the iOS part is no longer maintained. So I suggest focussing on the algorithm part.

hi，Can you send me the code of the previous IOS part ？my e-mail adress is 513489330@qq.com
